# Generated by Django 4.0.1 on 2022-01-13 18:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('positive', models.FloatField()),
                ('negative', models.FloatField()),
                ('neutral', models.FloatField()),
                ('wordcloud_pos', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('wordcloud_neg', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
