# Generated by Django 4.0.1 on 2022-01-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='negative',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='neutral',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='positive',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
