# Generated by Django 4.0.1 on 2022-01-14 15:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0002_alter_sentiment_negative_alter_sentiment_neutral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='wordcloud_neg',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='wordcloud_pos',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image'),
        ),
    ]
