# Generated by Django 4.0.1 on 2022-01-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0003_alter_sentiment_email_alter_sentiment_wordcloud_neg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='wordcloud_neg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='wordcloud_pos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
